apiVersion: v2
name: lse-stack
description: LSE stock + news + Grafana on k3s
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: influxdb2
    version: "~2.1.0"
    repository: "https://helm.influxdata.com/"
  - name: grafana
    version: "~8.6.0"
    repository: "https://grafana.github.io/helm-charts"
