apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: influx-config
  name: influx-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
