apiVersion: v1
data:
  app.env: |
    # ------------ InfluxDB (v2) -------------
    INFLUXDB_ORG=stocks
    INFLUXDB_BUCKET=lse
    INFLUXDB_ADMIN_USER=admin
    INFLUXDB_ADMIN_PASSWORD=admin12345
    INFLUXDB_ADMIN_TOKEN=devtoken-please-change-me

    # Influx init vars (put them here so compose doesn't need ${...} expansion)
    DOCKER_INFLUXDB_INIT_MODE=setup
    DOCKER_INFLUXDB_INIT_USERNAME=admin
    DOCKER_INFLUXDB_INIT_PASSWORD=admin12345
    DOCKER_INFLUXDB_INIT_ORG=stocks
    DOCKER_INFLUXDB_INIT_BUCKET=lse
    DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=devtoken-please-change-me

    # ------------ Grafana -------------------
    GRAFANA_ADMIN_USER=admin
    GRAFANA_ADMIN_PASSWORD=admin
    # Grafana reads these envs directly:
    GF_SECURITY_ADMIN_USER=admin
    GF_SECURITY_ADMIN_PASSWORD=admin

    # ------------ Fetcher -------------------
    # Comma-separated list of tickers (.L for LSE)
    TICKERS=VOD.L,HSBA.L,BP.L,AAPL,MSFT,GOOGL
    FETCH_INTERVAL_SECONDS=60
    YF_INTERVAL=1m
    YF_PERIOD=5d          # for 1m bars, Yahoo ~7d max; you can use 7d if you like
    BACKFILL_ON_START=true
    BACKFILL_PERIOD=5d

    # ------------- News ---------------------
    NEWS_BACKFILL_ON_START=true
    NEWS_BACKFILL_DAYS=30
    NEWS_POLL_SECONDS=900
    NEWS_LOOKBACK_HOURS=24
    NEWS_FILTER_REQUIRE_TICKER=false
    NEWS_KEYWORDS=HSBC,Vodafone,BP,Apple,Microsoft,Alphabet


    INFLUX_TOKEN=devtoken-please-change-me
    INFLUX_ORG=stocks
    INFLUX_BUCKET=lse
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: news
  name: news-cm0
