apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lse.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  INFLUX_URL: "http://{{ include "lse.fullname" . }}-influxdb2"
  INFLUX_ORG: "{{ .Values.influxdb2.adminUser.organization }}"
  INFLUX_BUCKET: "{{ .Values.influxdb2.adminUser.bucket }}"
  INFLUX_TOKEN: "{{ .Values.influxdb2.adminUser.token }}"
